services:
  mysql:
    image: mysql:8.0
    container_name: kurchive-mysql-dev
    restart: always
    env_file:
      - .local.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    networks:
      - kurchive-net

  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile.local
    container_name: kurchive-backend-dev
    restart: on-failure
    env_file:
      - .local.env
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    networks:
      - kurchive-net
    volumes:
      - ./BE:/app/BE   # BE 폴더가 /app으로 마운트됨
      - /app/node_modules
    command: bash
    tty: true
    stdin_open: true


volumes:
  mysql_data_dev:

networks:
  kurchive-net:
    driver: bridge
