FROM python:3.11

WORKDIR /app

# 시스템 패키지 (pymysql, dotenv 등 설치용)
RUN pip install --upgrade pip

# requirements.txt
COPY requirements.txt ./
RUN pip install -r requirements.txt || true

# 소스 복사
COPY . .

